add posting of releases

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -6,6 +6,8 @@ name: Python application
 on:
   push:
     branches: [ "master", "development" ]
+    tags:
+      - '[0-9]+.[0-9]+.[0-9]+'
   pull_request:
     branches: [ "master", "development" ]
 
@@ -13,7 +15,7 @@ permissions:
   contents: read
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
     timeout-minutes: 2
     steps:
@@ -40,3 +42,112 @@ jobs:
     - name: Test with pytest (no xvfb)
       run: |
         pytest
+
+  build:
+    needs: test
+    strategy:
+      matrix:
+        include:
+          - os: ubuntu-latest
+            arch: x64
+          - os: ubuntu-latest
+            arch: arm64
+          - os: windows-latest
+            arch: x64
+          - os: macos-latest # x64 runner
+            arch: x64
+          - os: macos-14 # arm64 runner for Apple Silicon
+            arch: arm64
+    runs-on: ${{ matrix.os }}
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
+    - name: Set up QEMU
+      if: matrix.arch == 'arm64' && startsWith(matrix.os, 'ubuntu')
+      uses: docker/setup-qemu-action@v3
+
+    - name: Create Release
+      id: create_release
+      if: ${{ startsWith(github.ref, 'refs/tags/') }}
+      uses: actions/create-release@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        tag_name: ${{ github.ref_name }}
+        release_name: Release ${{ github.ref_name }}
+        draft: false
+        prerelease: false
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements_gui.txt
+        pip install cx_freeze
+
+    - name: Build with cx_Freeze
+      run: python setup.py build
+
+    - name: Determine Build Path and Archive Name
+      id: build_info
+      shell: bash
+      run: |
+        BUILD_DIR=$(find build -maxdepth 1 -type d -name 'exe.*' -print -quit)
+        if [[ -z "$BUILD_DIR" ]]; then
+          echo "Build directory not found!"
+          exit 1
+        fi
+        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_OUTPUT
+
+        ref_name="${{ github.ref_name }}"
+        ref_name_sanitized="${ref_name//\//-}"
+
+        if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
+          VERSION_NAME="$ref_name_sanitized"
+        else
+          VERSION_NAME="$ref_name_sanitized-${{ github.sha }}"
+        fi
+
+        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
+          ARCHIVE_NAME="mp3-tag-rebuilder-$VERSION_NAME-${{ matrix.os }}-${{ matrix.arch }}.zip"
+          echo "ASSET_CONTENT_TYPE=application/zip" >> $GITHUB_OUTPUT
+        else
+          ARCHIVE_NAME="mp3-tag-rebuilder-$VERSION_NAME-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
+          echo "ASSET_CONTENT_TYPE=application/gzip" >> $GITHUB_OUTPUT
+        fi
+        echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
+
+    - name: Archive Build Artifacts (Windows)
+      if: matrix.os == 'windows-latest'
+      shell: powershell
+      run: |
+        cd ${{ steps.build_info.outputs.BUILD_DIR }}
+        Compress-Archive -Path * -DestinationPath ${{ github.workspace }}/${{ steps.build_info.outputs.ARCHIVE_NAME }}
+
+    - name: Archive Build Artifacts (Linux/macOS)
+      if: matrix.os != 'windows-latest'
+      shell: bash
+      run: tar czf ${{ steps.build_info.outputs.ARCHIVE_NAME }} -C ${{ steps.build_info.outputs.BUILD_DIR }} .
+
+    - name: Upload Build Artifact
+      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ steps.build_info.outputs.ARCHIVE_NAME }}
+        path: ${{ steps.build_info.outputs.ARCHIVE_NAME }}
+
+    - name: Upload Release Asset
+      if: ${{ startsWith(github.ref, 'refs/tags/') }}
+      uses: actions/upload-release-asset@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.create_release.outputs.upload_url }}
+        asset_path: ./${{ steps.build_info.outputs.ARCHIVE_NAME }}
+        asset_name: ${{ steps.build_info.outputs.ARCHIVE_NAME }}
+        asset_content_type: ${{ steps.build_info.outputs.ASSET_CONTENT_TYPE }}
